In [2]:
import numpy as np

In [24]:
a = np.array([1 , 2 , 3 , 4])
print(a)
print(type(a))
print(a.size)
print(a .ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
4
1


In [25]:
b = np.array([[1 , 2, 3] , [5 , 6 , 7 ]])
print(b[0,0])
print(b.shape)
c = a.reshape(2,2)
print(c)


1
(2, 3)
[[1 2]
 [3 4]]


In [34]:
d = np.array([[1,2,3] , [4,5,6]])
print(d)
d = d.reshape(3,2)
print("After Reshape: " )
print(d)

[[1 2 3]
 [4 5 6]]
After Reshape: 
[[1 2]
 [3 4]
 [5 6]]


In [41]:
e = np.ones((3 , 4))
#fill with ones , given size of 2d array
f = np.zeros((3,4))
#fill with zeros , given size of 2d array

print("ones: ")
print(e)
print("zeros: " )
print(f)
g = np.arange(5)
# 1d array -> from 0 to n-1
print(g)
v = np.full((2, 3,) , 8)
#           2-d size ,fill with 8
print(v)

ones: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
zeros: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0 1 2 3 4]
[[8 8 8]
 [8 8 8]]


In [42]:
i = np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
r = np.random.random((4,5))
print(r)


[[0.97056267 0.55842506 0.82346759 0.91378567 0.25579142]
 [0.37245262 0.23081236 0.73652915 0.01292604 0.78920751]
 [0.40822767 0.05296387 0.22794026 0.08504341 0.97975237]
 [0.36217732 0.08781245 0.38859105 0.16682752 0.20659506]]


In [63]:
g = np.arange(12)
# print(g)
g = g.reshape(3 , 4)
g += 1

print(g[1:3 , 1:3])

[[ 6  7]
 [10 11]]


In [64]:
a = np.ones((5,5))
a[1:4 , 1 :4] = 0
a[2:3 , 2 :3] = 9
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [66]:
h = np.array([[1,2,3,4,5] , [6,7,8,9,10]])
print(h[-1 , -4 : -1])

[7 8 9]


In [70]:
j = a.copy()
j[2][2] = 77
print(j)
print(a)
#here a and j are different but if i write j = a then it is passed by reference not by value

[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0. 77.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [77]:
k = np.array([1,2,3])
l = np.array([4,5,6])
print(np.add(k,l))
print(np.divide(k,l))
print(np.subtract(k,l))
print(np.multiply(k,l))

[5 7 9]
[0.25 0.4  0.5 ]
[-3 -3 -3]
[ 4 10 18]


In [81]:
print(b)
print(np.sum(b))
print(np.sum(b , axis = 0)) # column-wise sum
print(np.sum(b , axis = 1)) # row-wise sum

[[1 2 3]
 [5 6 7]]
24
[ 6  8 10]
[ 6 18]


In [84]:
print(b.T) # Transpose

[[1 5]
 [2 6]
 [3 7]]
